/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor */
package formularios;

import conectar_almacen.Database; //llamamos la conexion a la BD para almacen
import static conectar_almacen.Database.getConexion;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class almacen extends javax.swing.JFrame {

    DefaultTableModel model;
    private Connection conexion;     
    private Statement st;     
    private ResultSet rs;
    
   
    /**
     * Creates new form almacen
     */
    public void Conectar(){
             try{ 
                conexion=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3307/fazuca","root","");                     
                st=conexion.createStatement(); 
                rs=st.executeQuery("select productos.codigo_de_barras, nombre_productos, marca,contenido,precio,cantidad,stock from productos inner join almacen on productos.codigo_de_barras = almacen.codigo_de_barras");
                        
                rs.first();
                
            }catch(SQLException err){ 
                JOptionPane.showMessageDialog(null,"Error "+err.getMessage()); 
            } 

    } 
          
    private void mostrar() {
        DefaultTableModel modelo = new DefaultTableModel();
        ResultSet rs = Database.getTabla(" select productos.codigo_de_barras, nombre_productos, marca,contenido,precio,cantidad,stock from productos inner join almacen on productos.codigo_de_barras = almacen.codigo_de_barras");
        modelo.setColumnIdentifiers(new Object[]{"codigo barras","producto","marca","contenido", "precio","stock"});
        try {
            while (rs.next()) {
                // añade los resultado a al modelo de tabla
                modelo.addRow(new Object[]{rs.getString("codigo_de_barras"), 
                    rs.getString("nombre_productos"), 
                    rs.getString("marca"),
                    rs.getString("contenido"), 
                    rs.getString("precio"), 
                    rs.getInt("stock")});
            }
            // asigna el modelo a la tabla
            jt_tabla_almacen.setModel(modelo);
        } catch (Exception e) {
            System.out.println(e);
        }

    }
    
    public almacen() {
        initComponents();
        mostrar(); 
        Conectar();
        limpiar();
        //jtf_cantidad_productos.setEnabled(false);
    }
    
    public void limpiar(){
        String codigo="";
        String nombre="";
        String marca="";
        String contenido="";
        Float precio = 0.0f;
        int cantidad=0;
        this.jtf_codigo_barras.setText(String.valueOf(codigo));
        this.jtf_nombre_producto.setText(String.valueOf(nombre));
        this.jtf_marca.setText(String.valueOf(marca));
        this.jtf_contenido.setText(String.valueOf(contenido));
        this.jtf_precio.setText(String.valueOf(precio));
        this.jtf_cantidad_productos.setText(String.valueOf(cantidad));
}

    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_tabla_almacen = new javax.swing.JTable();
        jtf_buscartodo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jb_salir = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jl_codigo_barras = new javax.swing.JLabel();
        jl_nombre_producto = new javax.swing.JLabel();
        jl_marca = new javax.swing.JLabel();
        jl_contenido = new javax.swing.JLabel();
        jl_precioU = new javax.swing.JLabel();
        jl_cantidad_productos = new javax.swing.JLabel();
        jtf_codigo_barras = new javax.swing.JTextField();
        jtf_nombre_producto = new javax.swing.JTextField();
        jtf_marca = new javax.swing.JTextField();
        jtf_contenido = new javax.swing.JTextField();
        jtf_precio = new javax.swing.JTextField();
        jtf_cantidad_productos = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jb_modificar = new javax.swing.JButton();
        jb_limpiar = new javax.swing.JButton();
        jb_guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Almacen");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jt_tabla_almacen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo barras", "Producto", "Marca", "contenido", "precio", "Stock"
            }
        ));
        jt_tabla_almacen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_tabla_almacenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_tabla_almacen);

        jtf_buscartodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtf_buscartodoKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("BUSCAR");

        jb_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/160_F_42459916_Yt7cH133dIcZbaIVMtkEanlXnOG149ZT.png"))); // NOI18N
        jb_salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_salirMouseClicked(evt);
            }
        });

        jl_codigo_barras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_codigo_barras.setText("Codigo de barras:");

        jl_nombre_producto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_nombre_producto.setText("Nombre del Producto:");

        jl_marca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_marca.setText("Marca:");

        jl_contenido.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_contenido.setText("Contenido:");

        jl_precioU.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_precioU.setText("Precio:");

        jl_cantidad_productos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jl_cantidad_productos.setText("Cantidad de Productos:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_codigo_barras)
                            .addComponent(jl_nombre_producto)
                            .addComponent(jl_contenido)
                            .addComponent(jl_marca))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jl_cantidad_productos)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jl_precioU)
                                .addGap(26, 26, 26)))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_cantidad_productos)
                    .addComponent(jtf_precio)
                    .addComponent(jtf_contenido)
                    .addComponent(jtf_marca, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jtf_nombre_producto))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(181, 181, 181)
                    .addComponent(jtf_codigo_barras, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jl_codigo_barras)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_nombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_nombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_marca))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_contenido))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_precioU))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_cantidad_productos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_cantidad_productos))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jtf_codigo_barras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(210, Short.MAX_VALUE)))
        );

        jb_modificar.setBackground(new java.awt.Color(0, 102, 255));
        jb_modificar.setForeground(new java.awt.Color(255, 255, 255));
        jb_modificar.setText("Modificar");
        jb_modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificarMouseClicked(evt);
            }
        });

        jb_limpiar.setBackground(new java.awt.Color(0, 102, 255));
        jb_limpiar.setForeground(new java.awt.Color(255, 255, 255));
        jb_limpiar.setText("limpiar");
        jb_limpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_limpiarMouseClicked(evt);
            }
        });

        jb_guardar.setBackground(new java.awt.Color(0, 102, 204));
        jb_guardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jb_guardar.setForeground(new java.awt.Color(255, 255, 255));
        jb_guardar.setText("Guardar");
        jb_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_guardarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jb_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jb_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jb_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(145, 145, 145))
                            .addComponent(jtf_buscartodo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jb_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_buscartodo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_buscartodoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtf_buscartodoKeyPressed
        
        String[] titulos = {"codigo barras","producto","marca","contenido", "precio","stock"};
        String[] registros = new String[50];

        String sql = "select  productos.codigo_de_barras, productos.nombre_productos, productos.marca,produtos.contenido,precio,stock from productos inner join almacen on productos.codigo_prod = almacen.codigo_prod WHERE codigo_de_barras LIKE '%" + jtf_buscartodo.getText() + "%' "
                + "OR nombre_productos LIKE '%" + jtf_buscartodo.getText() + "%'"
                + "OR marca LIKE '%" + jtf_buscartodo.getText() + "%'";
        model = new DefaultTableModel(null, titulos);
        Database cc = new Database();
        Connection cn = getConexion();
        try {
            Statement st = (Statement) cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                registros[0] = rs.getString("codigo_de_barras");
                registros[1] = rs.getString("nombre_productos");
                registros[2] = rs.getString("marca");
                registros[3] = rs.getString("contenido");
                registros[4] = rs.getString("precio");
                registros[5] = rs.getString("stock");
                model.addRow(registros);
            }
            jt_tabla_almacen.setModel(model);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

    }//GEN-LAST:event_jtf_buscartodoKeyPressed

    private void jb_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_salirMouseClicked
        menu menu = new menu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jb_salirMouseClicked

    private void jb_limpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_limpiarMouseClicked
        limpiar();
    }//GEN-LAST:event_jb_limpiarMouseClicked

    private void jt_tabla_almacenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_tabla_almacenMouseClicked
        int rec = this.jt_tabla_almacen.getSelectedRow();
        this.jtf_codigo_barras.setText(jt_tabla_almacen.getValueAt(rec, 0).toString());
        this.jtf_nombre_producto.setText(jt_tabla_almacen.getValueAt(rec, 1).toString());
        this.jtf_marca.setText(jt_tabla_almacen.getValueAt(rec, 2).toString());
        this.jtf_contenido.setText(jt_tabla_almacen.getValueAt(rec, 3).toString());
        this.jtf_precio.setText(jt_tabla_almacen.getValueAt(rec, 4).toString());
        
    }//GEN-LAST:event_jt_tabla_almacenMouseClicked

    private void jb_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_guardarMouseClicked
        try{
                String codigo=this.jtf_codigo_barras.getText();
                String nombre=this.jtf_nombre_producto.getText(); 
                String marca=this.jtf_marca.getText(); 
                String contenido=this.jtf_contenido.getText();
                float precio=Float.parseFloat(this.jtf_precio.getText());
                int cantidad=Integer.parseInt(this.jtf_cantidad_productos.getText());
                
                st.executeUpdate("Insert into productos (codigo_de_barras,nombre_productos,marca,contenido,precio_prov,cantidad) values ('"+ codigo +"','"+nombre+"','"+marca+"','"+contenido+"','"+precio+"','"+cantidad+"');"); 
                 st.executeUpdate("insert into almacen (precio,stock,codigo_de_barras)values ('"+ precio +"','"+cantidad+"','"+ codigo +"');"); 
                JOptionPane.showMessageDialog(null,"Guardado con exito "); 
               
            mostrar();
            Conectar();
            limpiar();
        } catch(Exception err) 
        { 
            JOptionPane.showMessageDialog(null,"Error "+err.getMessage()); 
        } 
    }//GEN-LAST:event_jb_guardarMouseClicked

    private void jb_modificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificarMouseClicked
         int confirmar = JOptionPane.showConfirmDialog(null, "¿Esta seguro de modificar el registro?");
        if(JOptionPane.OK_OPTION==confirmar) {
        try{
                String codigo=this.jtf_codigo_barras.getText();
                String nombre=this.jtf_nombre_producto.getText(); 
                String marca=this.jtf_marca.getText(); 
                String contenido=this.jtf_contenido.getText();
                float precio=Float.parseFloat(this.jtf_precio.getText());
                int cantidad=Integer.parseInt(this.jtf_cantidad_productos.getText()); 
                st.executeUpdate("UPDATE productos SET nombre_productos='"+nombre+"',marca='"+marca+"',contenido='"+contenido+"',precio_prov='"+precio+"',cantidad='"+cantidad+"' WHERE codigo_de_barras = '"+codigo+"';");
                st.executeUpdate("UPDATE almacen  SET precio='"+ precio +"' WHERE codigo_de_barras = '"+codigo+"';");
                
                JOptionPane.showMessageDialog(null,"Guardado con exito "); 
            mostrar();
            Conectar();
            limpiar();
        } catch(Exception err) 
        { 
            JOptionPane.showMessageDialog(null,"Error "+err.getMessage()); 
        } 
        }
    }//GEN-LAST:event_jb_modificarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new almacen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_limpiar;
    private javax.swing.JButton jb_modificar;
    private javax.swing.JToggleButton jb_salir;
    private javax.swing.JLabel jl_cantidad_productos;
    private javax.swing.JLabel jl_codigo_barras;
    private javax.swing.JLabel jl_contenido;
    private javax.swing.JLabel jl_marca;
    private javax.swing.JLabel jl_nombre_producto;
    private javax.swing.JLabel jl_precioU;
    private javax.swing.JTable jt_tabla_almacen;
    private javax.swing.JTextField jtf_buscartodo;
    private javax.swing.JTextField jtf_cantidad_productos;
    private javax.swing.JTextField jtf_codigo_barras;
    private javax.swing.JTextField jtf_contenido;
    private javax.swing.JTextField jtf_marca;
    private javax.swing.JTextField jtf_nombre_producto;
    private javax.swing.JTextField jtf_precio;
    // End of variables declaration//GEN-END:variables
}
